/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package censusrecordanalysis.view;

import censusrecordanalysis.controller.CityController;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import censusrecordanalysis.model.Country;
import censusrecordanalysis.model.States;
import censusrecordanalysis.model.Houses;
import censusrecordanalysis.model.Persons;

import java.util.ArrayList;
//import censusrecordanalysis.controller.*;
import censusrecordanalysis.controller.HouseController;
import censusrecordanalysis.controller.StateController;
import censusrecordanalysis.model.Cities;

import java.awt.Color;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author indra
 */
public class AddRecords extends javax.swing.JFrame {

    ArrayList<Country> countryObj1 = new ArrayList<Country>();
    ArrayList<States> stateObj1 = new ArrayList<States>();
    ArrayList<Houses> houseObj1 = new ArrayList<Houses>();
    ArrayList<Cities> cityObj1 = new ArrayList<Cities>();
    Persons person=new Persons(); 
    public Country cou = new Country();
    public States stat = new States();
    public Cities cit = new Cities();
    public Houses hou = new Houses();

    /**
     * Creates new form AddRecords
     */
    public AddRecords(ArrayList<Country> countryObj) {
        initComponents();
        countryObj1 = countryObj;
        //   System.out.println(countryObj.size());
        Country cx = new Country();
        //System.out.println(countryObj[0].getId()+":"+countryObj[0].getCountryFullname());
        combCountry.addItem("Select Country");
        for (Country c : countryObj) {
            //this.combCountry.setModel();
            combCountry.addItem(c.toString());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panelBackground = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCountry = new javax.swing.JLabel();
        combCountry = new javax.swing.JComboBox<String>();
        lblState = new javax.swing.JLabel();
        bombState = new javax.swing.JComboBox<String>();
        combCity = new javax.swing.JComboBox<String>();
        lblCity = new javax.swing.JLabel();
        lblHouse = new javax.swing.JLabel();
        combHouseNumb = new javax.swing.JComboBox<String>();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblEduLvl = new javax.swing.JLabel();
        lblEmployment = new javax.swing.JLabel();
        lblPaddress = new javax.swing.JLabel();
        lblMaddress = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtMailingAddress = new javax.swing.JTextField();
        btnSubmitRecord = new javax.swing.JButton();
        combGender = new javax.swing.JComboBox<String>();
        combEmployment = new javax.swing.JComboBox<String>();
        jComboReligion = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        addMenu = new javax.swing.JMenuBar();
        menuCountry = new javax.swing.JMenu();
        menuState = new javax.swing.JMenu();
        menuCity = new javax.swing.JMenu();
        menuHouse = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Personal Entry Forms");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 153, 207));
        setName("frameAdd"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1096, 700));

        panelBackground.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("Personal Information Entry Form");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblCountry.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblCountry.setForeground(new java.awt.Color(0, 102, 153));
        lblCountry.setText("Country Name");

        combCountry.setBackground(new java.awt.Color(0, 153, 204));
        combCountry.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        combCountry.setForeground(new java.awt.Color(0, 153, 204));
        combCountry.setToolTipText("");
        combCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combCountryItemStateChanged(evt);
            }
        });
        combCountry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combCountryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                combCountryMouseEntered(evt);
            }
        });
        combCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combCountryActionPerformed(evt);
            }
        });

        lblState.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblState.setForeground(new java.awt.Color(0, 102, 153));
        lblState.setText("State Name");

        bombState.setBackground(new java.awt.Color(0, 153, 204));
        bombState.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        bombState.setForeground(new java.awt.Color(0, 153, 204));
        bombState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select State", "IOWA" }));
        bombState.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bombStateItemStateChanged(evt);
            }
        });
        bombState.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bombStateMouseClicked(evt);
            }
        });

        combCity.setBackground(new java.awt.Color(0, 153, 204));
        combCity.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        combCity.setForeground(new java.awt.Color(0, 153, 204));
        combCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select City", "Fairfield" }));
        combCity.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combCityItemStateChanged(evt);
            }
        });
        combCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combCityActionPerformed(evt);
            }
        });

        lblCity.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblCity.setForeground(new java.awt.Color(0, 102, 153));
        lblCity.setText("City Name");

        lblHouse.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblHouse.setForeground(new java.awt.Color(0, 102, 153));
        lblHouse.setText("House Number");

        combHouseNumb.setBackground(new java.awt.Color(0, 153, 204));
        combHouseNumb.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        combHouseNumb.setForeground(new java.awt.Color(0, 153, 204));
        combHouseNumb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select House Number", "10012" }));
        combHouseNumb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combHouseNumbItemStateChanged(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 102, 153));
        lblName.setText("Name");

        lblAge.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblAge.setForeground(new java.awt.Color(0, 102, 153));
        lblAge.setText("Age");

        lblSex.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblSex.setForeground(new java.awt.Color(0, 102, 153));
        lblSex.setText("Gender");

        lblSSN.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblSSN.setForeground(new java.awt.Color(0, 102, 153));
        lblSSN.setText("SS Number");

        lblEduLvl.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblEduLvl.setForeground(new java.awt.Color(0, 102, 153));
        lblEduLvl.setText("Education Level");

        lblEmployment.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblEmployment.setForeground(new java.awt.Color(0, 102, 153));
        lblEmployment.setText("Employment Status");

        lblPaddress.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblPaddress.setForeground(new java.awt.Color(0, 102, 153));
        lblPaddress.setText("Religion");

        lblMaddress.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblMaddress.setForeground(new java.awt.Color(0, 102, 153));
        lblMaddress.setText("Mailing Address");

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 153, 204));

        txtAge.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtAge.setForeground(new java.awt.Color(0, 153, 204));

        txtSSN.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtSSN.setForeground(new java.awt.Color(0, 153, 204));

        txtMailingAddress.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtMailingAddress.setForeground(new java.awt.Color(0, 153, 204));

        btnSubmitRecord.setBackground(new java.awt.Color(0, 153, 204));
        btnSubmitRecord.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSubmitRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitRecord.setText("Submit");
        btnSubmitRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitRecordMouseClicked(evt);
            }
        });

        combGender.setBackground(new java.awt.Color(0, 153, 204));
        combGender.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        combGender.setForeground(new java.awt.Color(0, 153, 204));
        combGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Gender", "Male", "Female", "Other" }));

        combEmployment.setBackground(new java.awt.Color(0, 153, 204));
        combEmployment.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        combEmployment.setForeground(new java.awt.Color(0, 153, 204));
        combEmployment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Employment Status", "Employed", "UnEmployed" }));

        jComboReligion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select religion", "Hindu", "Christian", "Islam", "Buddhist", "Other" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select education", "Preschool", "Elementary School", "Middle School", "High School", "Under Graduate", "Graduate", "Post Graduate", "Doctorate"}));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCountry)
                    .addComponent(lblPaddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCity)
                    .addComponent(lblEduLvl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSSN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmployment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMailingAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(combCountry, 0, 200, Short.MAX_VALUE)
                                    .addComponent(combCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblState)
                                    .addComponent(lblHouse)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(combGender, javax.swing.GroupLayout.Alignment.LEADING, 0, 386, Short.MAX_VALUE)
                                .addComponent(txtAge, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(btnSubmitRecord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bombState, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combHouseNumb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(combEmployment, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountry)
                    .addComponent(combCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblState)
                    .addComponent(bombState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(combCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHouse)
                    .addComponent(combHouseNumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSex)
                    .addComponent(combGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEduLvl)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployment)
                    .addComponent(combEmployment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaddress)
                    .addComponent(jComboReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaddress)
                    .addComponent(txtMailingAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmitRecord)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        addMenu.setBackground(new java.awt.Color(255, 255, 255));
        addMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addMenu.setForeground(new java.awt.Color(255, 255, 255));

        menuCountry.setBackground(new java.awt.Color(255, 255, 255));
        menuCountry.setForeground(new java.awt.Color(0, 102, 153));
        menuCountry.setText("Add Country");
        menuCountry.setToolTipText("Add Country Name");
        menuCountry.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        menuCountry.setMargin(new java.awt.Insets(5, 10, 5, 5));
        menuCountry.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuCountryMenuSelected(evt);
            }
        });
        menuCountry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCountryMouseClicked(evt);
            }
        });
        menuCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCountryActionPerformed(evt);
            }
        });
        addMenu.add(menuCountry);

        menuState.setBackground(new java.awt.Color(255, 255, 255));
        menuState.setForeground(new java.awt.Color(0, 102, 153));
        menuState.setText("Add State");
        menuState.setToolTipText("Add Country Name");
        menuState.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        menuState.setMargin(new java.awt.Insets(5, 10, 5, 5));
        menuState.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuStateMouseClicked(evt);
            }
        });
        menuState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStateActionPerformed(evt);
            }
        });
        addMenu.add(menuState);

        menuCity.setBackground(new java.awt.Color(255, 255, 255));
        menuCity.setForeground(new java.awt.Color(0, 102, 153));
        menuCity.setText("Add City");
        menuCity.setToolTipText("Add Country Name");
        menuCity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        menuCity.setMargin(new java.awt.Insets(5, 10, 5, 5));
        menuCity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCityMouseClicked(evt);
            }
        });
        addMenu.add(menuCity);

        menuHouse.setBackground(new java.awt.Color(255, 255, 255));
        menuHouse.setForeground(new java.awt.Color(0, 102, 153));
        menuHouse.setText("Add House");
        menuHouse.setToolTipText("Add Country Name");
        menuHouse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        menuHouse.setMargin(new java.awt.Insets(5, 10, 5, 5));
        menuHouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHouseMouseClicked(evt);
            }
        });
        addMenu.add(menuHouse);

        setJMenuBar(addMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1124, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCountryActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AddCountryName().setVisible(true);
    }//GEN-LAST:event_menuCountryActionPerformed

    private void menuStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStateActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuStateActionPerformed

    private void combCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combCityActionPerformed

    private void menuCountryMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuCountryMenuSelected
        // TODO add your handling code here:

    }//GEN-LAST:event_menuCountryMenuSelected

    private void menuCountryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCountryMouseClicked
        // TODO add your handling code here:
        menuCountry.setBackground(Color.WHITE);
        new AddCountryName().setVisible(true);
    }//GEN-LAST:event_menuCountryMouseClicked

    private void menuStateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuStateMouseClicked
        // TODO add your handling code here:
        new AddStateName().setVisible(true);
    }//GEN-LAST:event_menuStateMouseClicked

    private void menuCityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCityMouseClicked
        // TODO add your handling code here:
        new AddCityName().setVisible(true);
    }//GEN-LAST:event_menuCityMouseClicked

    private void menuHouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHouseMouseClicked
        // TODO add your handling code here:
        new AddHouseNumber().setVisible(true);
    }//GEN-LAST:event_menuHouseMouseClicked

    private void combCountryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combCountryMouseClicked

    }//GEN-LAST:event_combCountryMouseClicked

    private void combCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combCountryActionPerformed

    private void combCountryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combCountryMouseEntered

    }//GEN-LAST:event_combCountryMouseEntered

    private void bombStateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bombStateMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_bombStateMouseClicked

    private void combCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combCountryItemStateChanged

        for (Country c : countryObj1) {
            //this.combCountry.setModel();
            if (c.toString().equals(combCountry.getSelectedItem())) {
                cou=c;
                try {

                    stateObj1 = null;
                    stateObj1 = new StateController().getStates(c.getId());
                    bombState.removeAllItems();
                    combCity.removeAllItems();
                    bombState.addItem("Select State");
                    combCity.addItem("Select City");
                    for (States s : stateObj1) {
                        //this.combCountry.setModel();
                        bombState.addItem(s.toString());
                       
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AddRecords.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(AddRecords.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            //this.combCountry.addItem(c.getCountryFullname());

        }

    }//GEN-LAST:event_combCountryItemStateChanged

    private void bombStateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bombStateItemStateChanged
        // TODO add your handling code here:
        //combCity.addItem("Select States");
        // if (bombState.getSelectedItem() != "Select States") {
        for (States s : stateObj1) {
                //System.out.println(s.toString().equals(bombState.getSelectedItem()));
            //this.combCountry.setModel();
            if (s.toString().equals(bombState.getSelectedItem())) {
                stat=s;
                try {
                //    System.out.println(s.getCountryId() + "sadfsd" + s.getId());
                    //cityObj1 = null;
                    cityObj1 = new CityController().getCities(s.getCountryId(), s.getId());
                //    System.out.println(cityObj1.size());

                    combCity.removeAllItems();
                    combHouseNumb.removeAllItems();
                    combCity.addItem("Select City");
                    combHouseNumb.addItem("Select House Number");
                    for (Cities c : cityObj1) {
                        //this.combCountry.setModel();
                        combCity.addItem(c.toString());

                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AddRecords.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(AddRecords.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            //this.combCountry.addItem(c.getCountryFullname());

        }


    }//GEN-LAST:event_bombStateItemStateChanged

    private void combCityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combCityItemStateChanged
        // TODO add your handling code here:
        for (Cities s : cityObj1) {
                //System.out.println(s.toString().equals(bombState.getSelectedItem()));
            //this.combCountry.setModel();
            if (s.toString().equals(combCity.getSelectedItem())) {
                cit=s;
                try {
                //    System.out.println(s.getId()+" This is house");
                    //cityObj1 = null;
                    //houseObj1 = 
                    houseObj1 = new HouseController().getHouseNos(s.getId());
                 //   System.out.println(houseObj1.size());

                    combHouseNumb.removeAllItems();
                    combHouseNumb.addItem("Select House Number");
                    for (Houses h : houseObj1) {
                        //this.combCountry.setModel();
                        combHouseNumb.addItem(h.toString());

                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AddRecords.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(AddRecords.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_combCityItemStateChanged

    private void btnSubmitRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitRecordMouseClicked
        // TODO add your handling code here:
        person.setAge(Integer.parseInt(txtAge.getText()));
        person.setCityId(cit.getId());
        person.setCountryId(cou.getId());
        person.setEducation(jComboBox2.getSelectedItem().toString());
        person.setEmployement(combEmployment.getSelectedItem().toString());
        person.setFullname(txtName.getText());
        person.setGender(combGender.getSelectedItem().toString());
        person.setHouseId(Integer.parseInt(hou.getHouseNo()));
        person.setMailingAddress(txtMailingAddress.getText());
        person.setReligions(jComboReligion.getSelectedItem().toString());
        person.setSsn(txtSSN.getText());
        person.setStateId(stat.getId());
        
       System.out.println(person.getAge()+":"+person.getCityId()+":"+person.getCountryId()+":"+person.getEducation()+":"+person.getEmployement()+":"+person.getFullname()+":"+person.getGender());
        
        
    }//GEN-LAST:event_btnSubmitRecordMouseClicked

    private void combHouseNumbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combHouseNumbItemStateChanged
        // TODO add your handling code here:
         for (Houses s : houseObj1) {
                //System.out.println(s.toString().equals(bombState.getSelectedItem()));
            //this.combCountry.setModel();
            if (s.toString().equals(combHouseNumb.getSelectedItem())) {
                hou=s;
    }//GEN-LAST:event_combHouseNumbItemStateChanged
         }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AddRecords().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar addMenu;
    private javax.swing.JComboBox<String> bombState;
    private javax.swing.JButton btnSubmitRecord;
    private javax.swing.JComboBox<String> combCity;
    private javax.swing.JComboBox<String> combCountry;
    private javax.swing.JComboBox<String> combEmployment;
    private javax.swing.JComboBox<String> combGender;
    private javax.swing.JComboBox<String> combHouseNumb;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboReligion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblEduLvl;
    private javax.swing.JLabel lblEmployment;
    private javax.swing.JLabel lblHouse;
    private javax.swing.JLabel lblMaddress;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPaddress;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblState;
    private javax.swing.JMenu menuCity;
    private javax.swing.JMenu menuCountry;
    private javax.swing.JMenu menuHouse;
    private javax.swing.JMenu menuState;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtMailingAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    // End of variables declaration//GEN-END:variables
}
